[package]
name = "ticket_resale_platform"
version = "1.0.0"
authors = []

[addresses]
TicketResalePlatform ='0xd40fa2201b15b9bf057724a3b08bc1901f3ddda30f2aa0ccb2f3ec033341dec2'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]




